const fs = require('fs');
const path = require('path');
const SVGSpriter = require('svg-sprite');

const iconsDir = path.join(__dirname, 'src/lib/icons');
const outputDir = path.join(__dirname, 'src/assets');

const spriter = new SVGSpriter({
  dest: outputDir,
  shape: {
    id: {
      generator: (name) => path.basename(name, '.svg'),
    },
  },
  mode: {
    symbol: {
      dest: '.',
      sprite: 'sprite.svg',
    },
  },
});

fs.readdirSync(iconsDir)
  .filter((file) => file.endsWith('.svg'))
  .forEach((file) => {
    const filepath = path.join(iconsDir, file);
    let svgContent = fs.readFileSync(filepath, 'utf-8');
    svgContent = svgContent.replace(/fill="#8E8E8E"/gi, 'fill="currentColor"');
    spriter.add(filepath, null, svgContent);
  });

spriter.compile((error, result) => {
  if (error) throw error;
  for (const mode in result) {
    for (const resource in result[mode]) {
      fs.mkdirSync(path.dirname(result[mode][resource].path), { recursive: true });
      fs.writeFileSync(result[mode][resource].path, result[mode][resource].contents);
    }
  }

  const iconNames = fs
    .readdirSync(iconsDir)
    .filter((file) => file.endsWith('.svg'))
    .map((file) => path.basename(file, '.svg'));

  fs.writeFileSync(
    path.join(__dirname, 'src/lib/icon/icon-names.ts'),
    `// Auto-generated by build-sprite.js — do not edit directly.\nexport const ICON_NAMES = ${JSON.stringify(iconNames, null, 2)} as const;\n`,
  );
  console.log('Sprite built at', path.join(outputDir, 'sprite.svg'));
});
